name: .NET Core

on:
  push:
    branches:    
      - '**'        # matches every branch


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.8.20417.9
    - name: Install dependencies
      run: dotnet restore **\TourOfHeroesTests\TourOfHeroesTests.sln
    - name: Build
      run: dotnet build **\TourOfHeroesTests\*.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test **\TourOfHeroesTests\*.sln --no-restore --verbosity normal